"""empty message

Revision ID: 1c57a2f24275
Revises: 72bd26dc7593
Create Date: 2023-03-14 20:35:51.002034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c57a2f24275'
down_revision = '72bd26dc7593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'deleted')
    # ### end Alembic commands ###
