"""empty message

Revision ID: 72bd26dc7593
Revises: 834b1a697901
Create Date: 2023-02-25 02:35:04.476105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bd26dc7593'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislikedPosts',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('laughedPosts',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('likedPosts',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('post', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('dislikes', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('laughs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'laughs')
    op.drop_column('post', 'dislikes')
    op.drop_column('post', 'likes')
    op.drop_table('likedPosts')
    op.drop_table('laughedPosts')
    op.drop_table('dislikedPosts')
    # ### end Alembic commands ###
