# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestArchiveposttest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1creatnewusertest(self):
    self.driver.get("http://127.0.0.1:5001/auth/login?next=%2F")
    self.driver.set_window_size(989, 805)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.LINK_TEXT, "Click to Register!").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("kareem14")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("kareem14@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("asasas")
    self.driver.find_element(By.ID, "password2").click()
    self.driver.find_element(By.ID, "password2").send_keys("asasas")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.close()
  
  def test_2createposttest(self):
    self.driver.get("http://127.0.0.1:5001/auth/login?next=%2F")
    self.driver.set_window_size(989, 805)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2)").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("kareem14")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("asasas")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "post").click()
    self.driver.find_element(By.ID, "post").send_keys("hello")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.close()
  
  def test_3deleteposttest(self):
    self.driver.get("http://127.0.0.1:5001/auth/login?next=%2F")
    self.driver.set_window_size(989, 805)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("kareem14")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("asasas")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "delete-btn-1").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.close()
  
  def test_4archivingposttest(self):
    self.driver.get("http://127.0.0.1:5001/auth/login?next=%2F")
    self.driver.set_window_size(989, 805)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("kareem14")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("asasas")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "post").click()
    self.driver.find_element(By.ID, "post").send_keys("hello")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Archive").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.ID, "like-count-2").click()
    self.driver.find_element(By.LINK_TEXT, "Archive").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.close()
  
