# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test2FATest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1RegisterUserTest(self):
    self.driver.get("http://127.0.0.1:5000/auth/login?next=%2F")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.LINK_TEXT, "Click to Register!").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("dackuaku")
    self.driver.find_element(By.CSS_SELECTOR, ".row").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("ackuaku@uwindsor.ca")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("apple")
    self.driver.find_element(By.ID, "password2").send_keys("apple")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.close()
  
  def test_2LoginTest(self):
    self.driver.get("http://127.0.0.1:5000/auth/login?next=%2F")
    self.driver.set_window_size(1219, 720)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("dackuaku")
    self.driver.find_element(By.ID, "password").send_keys("apple")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.close()
  
  def test_3Enable2FATest(self):
    self.driver.get("http://127.0.0.1:5000/auth/login?next=%2F")
    self.driver.set_window_size(945, 1012)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("dackuaku")
    self.driver.find_element(By.ID, "password").send_keys("apple")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(3)").click()
    self.driver.find_element(By.ID, "yes").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(8)").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.close()
  
  def test_42FALoginTest(self):
    self.driver.get("http://127.0.0.1:5000/auth/login?next=%2F")
    self.driver.set_window_size(945, 1012)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("dackuaku")
    self.driver.find_element(By.ID, "password").send_keys("apple")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "verificationCode").click()
    self.driver.find_element(By.ID, "verificationCode").send_keys("DnV$HE$y7PEzUnjZ")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.close()
  
  def test_52FAInvalidCodeTest(self):
    self.driver.get("http://127.0.0.1:5000/auth/login?next=%2F")
    self.driver.set_window_size(945, 1012)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("dackuaku")
    self.driver.find_element(By.ID, "password").send_keys("apple")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "verificationCode").click()
    self.driver.find_element(By.ID, "verificationCode").send_keys("happy birthday Saad")
    self.driver.find_element(By.ID, "verificationCode").send_keys(Keys.ENTER)
    self.driver.close()
  
  def test_6Disable2FATest(self):
    self.driver.get("http://127.0.0.1:5000/auth/login?next=%2F")
    self.driver.set_window_size(945, 1012)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("dackuaku")
    self.driver.find_element(By.ID, "password").send_keys("apple")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "verificationCode").click()
    self.driver.find_element(By.ID, "verificationCode").send_keys("DnV$HE$y7PEzUnjZ")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.ID, "no").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(8)").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("dackuaku")
    self.driver.find_element(By.ID, "password").send_keys("apple")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.close()
  
